version: '3.7'
services:
  database:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: mysql_cour
      MYSQL_USER: isox
      MYSQL_PASSWORD: toor
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./storage-db:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge